# Generated by Django 4.2.4 on 2023-09-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForumInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=1000, verbose_name='Comentarios')),
                ('calification', models.IntegerField(default=0, verbose_name='Calificacion')),
            ],
            options={
                'verbose_name': 'Comentarios',
                'db_table': 'Comentarios',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Missions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='NombreMision')),
                ('numberMission', models.PositiveIntegerField(verbose_name='NumeroMisiones')),
                ('objetive', models.CharField(max_length=250, verbose_name='ObjetivoMision')),
                ('typeMission', models.CharField(max_length=250, verbose_name='TipoMision')),
                ('result', models.CharField(max_length=250, verbose_name='ResultadoMision')),
                ('age', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Misiones',
                'db_table': 'Misiones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PersonalizedAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeAdvice', models.CharField(max_length=250, verbose_name='TipoAsesoria')),
                ('topic', models.CharField(max_length=250, verbose_name='TemaAsesoria')),
                ('suggestion', models.TextField(max_length=250, verbose_name='Sugerencias')),
                ('historialAdvice', models.CharField(max_length=250, verbose_name='HistorialAsesorias')),
                ('missions', models.ManyToManyField(to='core.missions', verbose_name='Asesoramiento_Misión')),
            ],
            options={
                'verbose_name': 'Asesorias',
                'db_table': 'Asesorias',
                'ordering': ['id'],
            },
        ),
    ]
