# Generated by Django 4.2.5 on 2023-09-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_personalizedadvice_options_remove_missions_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Psicólogo', 'Psicólogo'), ('Aprendiz', 'Aprendiz')], max_length=15, verbose_name='Rol')),
            ],
        ),
    ]
