# Generated by Django 4.2.5 on 2023-09-22 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='role',
            field=models.CharField(choices=[('Psicólogo', 'Psicólogo'), ('Aprendiz', 'Aprendiz')], max_length=15, verbose_name='rol'),
        ),
    ]
