# Generated by Django 4.2.5 on 2023-09-22 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_alter_usuarios_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='role',
            field=models.CharField(blank=True, choices=[('Psicólogo', 'Psicólogo'), ('Aprendiz', 'Aprendiz')], max_length=15, null=True, verbose_name='rol'),
        ),
    ]
